#### 공공데이터 포털
* https://www.data.go.kr/index.do
* 월별 주야별 교통사고 통계 - https://www.data.go.kr/data/15070318/fileData.do#layer_data_infomation

### 절대경로
* 웹페이지나 파일이 가진 고유한 경로
* 최상위 디렉토리 포함

### 상대경로
* 현재 위치한 곳이 기준
* / 는 루트
* ./ 는 현재 위치
* ../는 현재 위치의 상위폴더
* ../../는 두단계 위의 상위폴더

In [1]:
%pwd
# 현재 위치 경로 파악

'C:\\Users\\yk999\\Desktop\\github\\Data Analysis\\Jupyter Tutorial'

In [2]:
import os
os.getcwd()

'C:\\Users\\yk999\\Desktop\\github\\Data Analysis\\Jupyter Tutorial'

In [15]:
from glob import glob
file_name = glob("data/*")[0]
file_name # 리스트

'data\\도로교통공단_월별 주야별 교통사고(2021).csv'

In [6]:
import pandas as pd

In [11]:
pd.read_csv("data/도로교통공단_월별 주야별 교통사고(2021).csv", encoding = 'cp949')

# pd.read_csv()에서 tab누르면 파일이름 자동완성
# UnicodeDecodeError -> encoding 에러
# "cp949" -> 한글 윈도우에서 사용되는 인코딩방식
# 현재 주피터노트북 파일과 같은 폴더에 있다면 파일명만 써도 OK
# data 폴더에 넣었다면 "data/도로교통공단_월별 주야별 교통사고(2021).csv"로 지정

    발생월 주야   사고건수  사망자수  중상자수   경상자수  부상신고자수
0     1  주   8821   107  2421   9631     707
1     1  야   6088    90  1627   6510     427
2     2  주   8756   107  2468   9681     670
3     2  야   5755    96  1572   6286     483
4     3  주  10274   128  2787  11163     820
5     3  야   6326    81  1775   6859     524
6     4  주  11032   119  3105  11935     819
7     4  야   6371    93  1878   6887     518
8     5  주  11025   154  3010  12132     922
9     5  야   6353   101  1762   6779     520
10    6  주  11310   124  3286  12244     865
11    6  야   6265   103  1733   6593     569
12    7  주  11408   139  3132  12435     892
13    7  야   6586   115  1829   7024     558
14    8  주  10407   129  2878  11541     854
15    8  야   6011   118  1638   6365     506
16    9  주  10869   131  2959  11885     856
17    9  야   6143   115  1747   6299     506
18   10  주  11229   156  3064  12129     882
19   10  야   7071   156  1935   7732     565
20   11  주  11223   163  3124  11890     922
21   11  야   6873   122  1884   7284     602
22   12  주  10318   149  2658  10936     916
23   12  야   6616   120  1633   7063     517

### 여러 파일을 한번에 로드

In [16]:
glob("data/store/*")

['data/store\\[붙임1] 소상공인시장진흥공단_상가(상권)정보_업종분류(2302)_및_연계표_v1.0(4).xlsx',
 'data/store\\[붙임2] 소상공인시장진흥공단_상가(상권)정보_데이터_코드집_v1.0(1).xlsx',
 'data/store\\[필독]파일 열람방법.txt',
 'data/store\\소상공인시장진흥공단_상가(상권)정보_강원_202306.csv',
 'data/store\\소상공인시장진흥공단_상가(상권)정보_경기_202306.csv',
 'data/store\\소상공인시장진흥공단_상가(상권)정보_경남_202306.csv',
 'data/store\\소상공인시장진흥공단_상가(상권)정보_경북_202306.csv',
 'data/store\\소상공인시장진흥공단_상가(상권)정보_광주_202306.csv',
 'data/store\\소상공인시장진흥공단_상가(상권)정보_대구_202306.csv',
 'data/store\\소상공인시장진흥공단_상가(상권)정보_대전_202306.csv',
 'data/store\\소상공인시장진흥공단_상가(상권)정보_부산_202306.csv',
 'data/store\\소상공인시장진흥공단_상가(상권)정보_서울_202306.csv',
 'data/store\\소상공인시장진흥공단_상가(상권)정보_세종_202306.csv',
 'data/store\\소상공인시장진흥공단_상가(상권)정보_울산_202306.csv',
 'data/store\\소상공인시장진흥공단_상가(상권)정보_인천_202306.csv',
 'data/store\\소상공인시장진흥공단_상가(상권)정보_전남_202306.csv',
 'data/store\\소상공인시장진흥공단_상가(상권)정보_전북_202306.csv',
 'data/store\\소상공인시장진흥공단_상가(상권)정보_제주_202306.csv',
 'data/store\\소상공인시장진흥공단_상가(상권)정보_충남_202306.csv',
 'data/store\\소상공인시장진흥공단_상가(상권)정보_충북_202306.csv']

In [18]:
glob("data/store/*.csv") 
# csv 파일만 불러오기

['data/store\\소상공인시장진흥공단_상가(상권)정보_강원_202306.csv',
 'data/store\\소상공인시장진흥공단_상가(상권)정보_경기_202306.csv',
 'data/store\\소상공인시장진흥공단_상가(상권)정보_경남_202306.csv',
 'data/store\\소상공인시장진흥공단_상가(상권)정보_경북_202306.csv',
 'data/store\\소상공인시장진흥공단_상가(상권)정보_광주_202306.csv',
 'data/store\\소상공인시장진흥공단_상가(상권)정보_대구_202306.csv',
 'data/store\\소상공인시장진흥공단_상가(상권)정보_대전_202306.csv',
 'data/store\\소상공인시장진흥공단_상가(상권)정보_부산_202306.csv',
 'data/store\\소상공인시장진흥공단_상가(상권)정보_서울_202306.csv',
 'data/store\\소상공인시장진흥공단_상가(상권)정보_세종_202306.csv',
 'data/store\\소상공인시장진흥공단_상가(상권)정보_울산_202306.csv',
 'data/store\\소상공인시장진흥공단_상가(상권)정보_인천_202306.csv',
 'data/store\\소상공인시장진흥공단_상가(상권)정보_전남_202306.csv',
 'data/store\\소상공인시장진흥공단_상가(상권)정보_전북_202306.csv',
 'data/store\\소상공인시장진흥공단_상가(상권)정보_제주_202306.csv',
 'data/store\\소상공인시장진흥공단_상가(상권)정보_충남_202306.csv',
 'data/store\\소상공인시장진흥공단_상가(상권)정보_충북_202306.csv']

In [19]:
file_csv = glob("data/store/*.csv") 
file_csv

['data/store\\소상공인시장진흥공단_상가(상권)정보_강원_202306.csv',
 'data/store\\소상공인시장진흥공단_상가(상권)정보_경기_202306.csv',
 'data/store\\소상공인시장진흥공단_상가(상권)정보_경남_202306.csv',
 'data/store\\소상공인시장진흥공단_상가(상권)정보_경북_202306.csv',
 'data/store\\소상공인시장진흥공단_상가(상권)정보_광주_202306.csv',
 'data/store\\소상공인시장진흥공단_상가(상권)정보_대구_202306.csv',
 'data/store\\소상공인시장진흥공단_상가(상권)정보_대전_202306.csv',
 'data/store\\소상공인시장진흥공단_상가(상권)정보_부산_202306.csv',
 'data/store\\소상공인시장진흥공단_상가(상권)정보_서울_202306.csv',
 'data/store\\소상공인시장진흥공단_상가(상권)정보_세종_202306.csv',
 'data/store\\소상공인시장진흥공단_상가(상권)정보_울산_202306.csv',
 'data/store\\소상공인시장진흥공단_상가(상권)정보_인천_202306.csv',
 'data/store\\소상공인시장진흥공단_상가(상권)정보_전남_202306.csv',
 'data/store\\소상공인시장진흥공단_상가(상권)정보_전북_202306.csv',
 'data/store\\소상공인시장진흥공단_상가(상권)정보_제주_202306.csv',
 'data/store\\소상공인시장진흥공단_상가(상권)정보_충남_202306.csv',
 'data/store\\소상공인시장진흥공단_상가(상권)정보_충북_202306.csv']

In [21]:
file_list = []
for file_csv_name in file_csv:
    print(file_csv_name)
    temp = pd.read_csv(file_csv_name)
    file_list.append(temp)

data/store\소상공인시장진흥공단_상가(상권)정보_강원_202306.csv

C:\Users\yk999\AppData\Local\Temp\ipykernel_25736\4249112912.py:4: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  temp = pd.read_csv(file_csv_name)

data/store\소상공인시장진흥공단_상가(상권)정보_경기_202306.csv

C:\Users\yk999\AppData\Local\Temp\ipykernel_25736\4249112912.py:4: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  temp = pd.read_csv(file_csv_name)

data/store\소상공인시장진흥공단_상가(상권)정보_경남_202306.csv

C:\Users\yk999\AppData\Local\Temp\ipykernel_25736\4249112912.py:4: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  temp = pd.read_csv(file_csv_name)

data/store\소상공인시장진흥공단_상가(상권)정보_경북_202306.csv

C:\Users\yk999\AppData\Local\Temp\ipykernel_25736\4249112912.py:4: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  temp = pd.read_csv(file_csv_name)

data/store\소상공인시장진흥공단_상가(상권)정보_광주_202306.csv

C:\Users\yk999\AppData\Local\Temp\ipykernel_25736\4249112912.py:4: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  temp = pd.read_csv(file_csv_name)

data/store\소상공인시장진흥공단_상가(상권)정보_대구_202306.csv

C:\Users\yk999\AppData\Local\Temp\ipykernel_25736\4249112912.py:4: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  temp = pd.read_csv(file_csv_name)

data/store\소상공인시장진흥공단_상가(상권)정보_대전_202306.csv

C:\Users\yk999\AppData\Local\Temp\ipykernel_25736\4249112912.py:4: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  temp = pd.read_csv(file_csv_name)

data/store\소상공인시장진흥공단_상가(상권)정보_부산_202306.csv

C:\Users\yk999\AppData\Local\Temp\ipykernel_25736\4249112912.py:4: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  temp = pd.read_csv(file_csv_name)

data/store\소상공인시장진흥공단_상가(상권)정보_서울_202306.csv

C:\Users\yk999\AppData\Local\Temp\ipykernel_25736\4249112912.py:4: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  temp = pd.read_csv(file_csv_name)

data/store\소상공인시장진흥공단_상가(상권)정보_세종_202306.csv
data/store\소상공인시장진흥공단_상가(상권)정보_울산_202306.csv

C:\Users\yk999\AppData\Local\Temp\ipykernel_25736\4249112912.py:4: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  temp = pd.read_csv(file_csv_name)

data/store\소상공인시장진흥공단_상가(상권)정보_인천_202306.csv

C:\Users\yk999\AppData\Local\Temp\ipykernel_25736\4249112912.py:4: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  temp = pd.read_csv(file_csv_name)

data/store\소상공인시장진흥공단_상가(상권)정보_전남_202306.csv

C:\Users\yk999\AppData\Local\Temp\ipykernel_25736\4249112912.py:4: DtypeWarning: Columns (2,35) have mixed types. Specify dtype option on import or set low_memory=False.
  temp = pd.read_csv(file_csv_name)

data/store\소상공인시장진흥공단_상가(상권)정보_전북_202306.csv

C:\Users\yk999\AppData\Local\Temp\ipykernel_25736\4249112912.py:4: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  temp = pd.read_csv(file_csv_name)

data/store\소상공인시장진흥공단_상가(상권)정보_제주_202306.csv

C:\Users\yk999\AppData\Local\Temp\ipykernel_25736\4249112912.py:4: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  temp = pd.read_csv(file_csv_name)

data/store\소상공인시장진흥공단_상가(상권)정보_충남_202306.csv

C:\Users\yk999\AppData\Local\Temp\ipykernel_25736\4249112912.py:4: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  temp = pd.read_csv(file_csv_name)

data/store\소상공인시장진흥공단_상가(상권)정보_충북_202306.csv

C:\Users\yk999\AppData\Local\Temp\ipykernel_25736\4249112912.py:4: DtypeWarning: Columns (2,35) have mixed types. Specify dtype option on import or set low_memory=False.
  temp = pd.read_csv(file_csv_name)

In [23]:
file_list[-1]

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,...,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
0,MA0101202210A0037302,강학수제주고기국수,NaN,I2,음식,I201,한식,I20105,국수/칼국수,I56112,...,4313011800112580000012049,NaN,충청북도 충주시 연수서3길 2,380963,27356,NaN,1,NaN,127.924396,36.985383
1,MA0101202210A0081461,끌림,NaN,I2,음식,I201,한식,I20101,백반/한정식,I56111,...,4380032021106380016014059,NaN,충청북도 단양군 가곡면 고수재로 432-4,395821,27021,NaN,NaN,NaN,128.387721,37.010755
2,MA0101202210A0086974,엘beauty&nail,NaN,S2,수리·개인,S207,이용·미용,S20703,네일숍,S96119,...,4315012000101620014024299,NaN,충청북도 제천시 신백로 111,390892,27178,NaN,1,NaN,128.225555,37.134812
3,MA010120220805430905,한결이엔지,NaN,M1,과학·기술,M109,기술 서비스,M10999,기타 엔지니어링 서비스업,M72129,...,4315012000101840014000001,NaN,충청북도 제천시 신백로16길 25,390892,27179,NaN,NaN,NaN,128.227820,37.131870
4,MA010120220805431250,레티컬렉션,NaN,G2,소매,G209,섬유·의복·신발 소매,G20902,여성 의류 소매업,G47412,...,4313012700108890000029070,NaN,충청북도 충주시 중앙로 36,380956,27408,NaN,NaN,NaN,127.927385,36.972760
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84699,MA0101202307A0073010,스튜디오양꾸,NaN,M1,과학·기술,M112,전문 디자인,M11203,시각 디자인업,M73203,...,4313010200100340000002471,NaN,충청북도 충주시 성서1길 12-1,380030,27393,NaN,1.0,NaN,127.932724,36.968996
84700,MA0101202307A0006560,중원당구클럽,NaN,R1,예술·스포츠,R103,스포츠 서비스,R10310,당구장,R91135,...,4313012200111190000023602,안림엘지아파트,충청북도 충주시 만리산10길 28,380779,27382,NaN,NaN,NaN,127.946245,36.970562
84701,MA0101202307A0090498,온가네육개장&칡냉면,NaN,I2,음식,I201,한식,I20101,백반/한정식,I56111,...,4313025021102640008000001,NaN,충청북도 충주시 주덕읍 신양2로 27,380884,27462,NaN,1.0,NaN,127.793743,36.972215
84702,MA0101202307A0064640,세겜디자인그룹,NaN,M1,과학·기술,M109,기술 서비스,M10901,건축 설계 및 관련 서비스업,M72111,...,4315025021102350000004776,중앙아파트,충청북도 제천시 봉양읍 제원로2길 7,390775,27114,NaN,2.0,NaN,128.126292,37.133634
84703,MA0101202307A0056153,평화가스,NaN,G2,소매,G214,연료 소매,G21403,가정용 연료 소매업,G47723,...,4377036031105940002000001,NaN,충청북도 음성군 생극면 오신로118번길 5,369843,27617,NaN,NaN,NaN,127.645943,37.012365

In [26]:
len(file_list)

17

In [25]:
df = pd.concat(file_list) # 하나로 합치기
df.shape

(2504940, 39)

In [27]:
df.head()

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,...,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
0,MA0101202210A0084547,금강산노래광장,NaN,I2,음식,I211,주점,I21101,일반 유흥 주점,I56211,...,4217010300007470000000086,파크장,강원특별자치도 동해시 송정로 11,240806,25789,NaN,지,NaN,129.127525,37.495265
1,MA010120220805430826,에이치속눈썹수강아카데미,NaN,S2,수리·개인,S207,이용·미용,S20702,피부 관리실,S96113,...,4211039021110620001000001,NaN,강원특별자치도 춘천시 동내면 외솔길19번길 80-36,200883,24401,NaN,NaN,NaN,127.758764,37.857831
2,MA010120220805430903,엔젤,NaN,I2,음식,I201,한식,I20101,백반/한정식,I55109,...,4277032022103660000008290,NaN,강원특별자치도 정선군 남면 민둥산로 175-13,233837,26148,NaN,NaN,NaN,128.792089,37.259788
3,MA010120220805430941,누베헤어,NaN,S2,수리·개인,S207,이용·미용,S20701,미용실,S96112,...,4211012500100440010000008,춘천파크자이,강원특별자치도 춘천시 스포츠타운길 460,200200,24472,NaN,3,NaN,127.707653,37.867744
4,MA010120220805430946,공차,NaN,I2,음식,I212,비알코올,I21201,카페,I56229,...,4213033023113500001000001,NaN,강원특별자치도 원주시 지정면 신지정로 211,220821,26354,NaN,NaN,NaN,127.872713,37.374189

In [28]:
df.tail()

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,...,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
84699,MA0101202307A0073010,스튜디오양꾸,NaN,M1,과학·기술,M112,전문 디자인,M11203,시각 디자인업,M73203,...,4313010200100340000002471,NaN,충청북도 충주시 성서1길 12-1,380030,27393,NaN,1.0,NaN,127.932724,36.968996
84700,MA0101202307A0006560,중원당구클럽,NaN,R1,예술·스포츠,R103,스포츠 서비스,R10310,당구장,R91135,...,4313012200111190000023602,안림엘지아파트,충청북도 충주시 만리산10길 28,380779,27382,NaN,NaN,NaN,127.946245,36.970562
84701,MA0101202307A0090498,온가네육개장&칡냉면,NaN,I2,음식,I201,한식,I20101,백반/한정식,I56111,...,4313025021102640008000001,NaN,충청북도 충주시 주덕읍 신양2로 27,380884,27462,NaN,1.0,NaN,127.793743,36.972215
84702,MA0101202307A0064640,세겜디자인그룹,NaN,M1,과학·기술,M109,기술 서비스,M10901,건축 설계 및 관련 서비스업,M72111,...,4315025021102350000004776,중앙아파트,충청북도 제천시 봉양읍 제원로2길 7,390775,27114,NaN,2.0,NaN,128.126292,37.133634
84703,MA0101202307A0056153,평화가스,NaN,G2,소매,G214,연료 소매,G21403,가정용 연료 소매업,G47723,...,4377036031105940002000001,NaN,충청북도 음성군 생극면 오신로118번길 5,369843,27617,NaN,NaN,NaN,127.645943,37.012365

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2504940 entries, 0 to 84703
Data columns (total 39 columns):
 #   Column     Dtype
---  ------     -----
 0   상가업소번호     object
 1   상호명        object
 2   지점명        object
 3   상권업종대분류코드  object
 4   상권업종대분류명   object
 5   상권업종중분류코드  object
 6   상권업종중분류명   object
 7   상권업종소분류코드  object
 8   상권업종소분류명   object
 9   표준산업분류코드   object
 10  표준산업분류명    object
 11  시도코드       int64
 12  시도명        object
 13  시군구코드      int64
 14  시군구명       object
 15  행정동코드      int64
 16  행정동명       object
 17  법정동코드      int64
 18  법정동명       object
 19  지번코드       int64
 20  대지구분코드     int64
 21  대지구분명      object
 22  지번본번지      float64
 23  지번부번지      float64
 24  지번주소       object
 25  도로명코드      float64
 26  도로명        object
 27  건물본번지      float64
 28  건물부번지      float64
 29  건물관리번호     object
 30  건물명        object
 31  도로명주소      object
 32  구우편번호      int64
 33  신우편번호      int64
 34  동정보        float64
 35  층정보        object
 36  호정보        float64
 37  경도         float64
 38  위도         float64
dtypes: float64(9), int64(8), object(22)
memory usage: 764.4+ MB